"""UI/system text extract+build for the three surfaces outside the .spt scripts.

  <game>/init2/config.fxf   XOR-0xFF Shift-JIS  (config screen hints, name window)
  <game>/spt/charaname.xtx  plain Shift-JIS     (character names)
  <game>/spt/namecol.xtx    plain Shift-JIS     (nameplate colors)

Source is each file's .orig snapshot; translations deploy onto the live file.

extract: each non-ASCII run -> a script/<file>.json entry { line, seg, key, original,
  translated:null, context }; '@' comment lines skipped, existing translations kept.
  Script-variable-name keys (pageNumberVarName / voiceNameChangeVar1) get a `note` and are
  never translated -- doing so breaks the engine's variable lookup ("var not found" at boot).
build: rebuild from .orig, substituting non-null SJIS-encodable "translated" runs, re-encode
  (+XOR for .fxf). names.json is authoritative for charaname/namecol, whose local
  translations are only fallbacks. config.fxf values are single whitespace-delimited
  tokens, so translations containing ASCII whitespace are rejected. All-null build is
  byte-identical.

Usage: python libraries/uitext.py {extract|build} --game DIR
"""
import json
import os
import re

from pipeline import NAMES, ensure_orig

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_DIR = os.path.join(ROOT, "script")
FILES = [
    # (name, xor?, path within a game install, use names.json glossary?)
    ("config.fxf", True, os.path.join("init2", "config.fxf"), False),
    ("charaname.xtx", False, os.path.join("spt", "charaname.xtx"), True),
    ("namecol.xtx", False, os.path.join("spt", "namecol.xtx"), True),
]
RUN = re.compile(r"[^\x00-\x7f]+")
# Keys whose value is a script variable name, not display text -- never translated.
PROTECT_KEY = re.compile(r"(?:VarName|Var\d+)$")
DEFAULT_GAME = os.path.join(ROOT, "game")


def load_name_map():
    if not os.path.exists(NAMES):
        return {}
    with open(NAMES, encoding="utf-8") as fh:
        return {k: v for k, v in json.load(fh).items() if v is not None}


def source_path(game_rel, game):
    """Pristine source for a UI file: the game's <asset>.orig snapshot."""
    orig = ensure_orig(os.path.join(game, game_rel))
    if not os.path.exists(orig):
        raise SystemExit(f"{game_rel}: not found in {game}")
    return orig


def load_lines(path, xor):
    raw = open(path, "rb").read()
    if xor:
        raw = bytes(b ^ 0xFF for b in raw)
    text = raw.decode("cp932")  # strict: fail loudly on anything unexpected
    lines = text.splitlines(keepends=True)
    # round-trip safety: rebuilding the file from decoded lines must be lossless
    if "".join(lines).encode("cp932") != raw:
        raise SystemExit(f"{path}: cp932 round-trip failed; do not edit this file with this tool")
    return lines


def extract(game=DEFAULT_GAME):
    os.makedirs(JSON_DIR, exist_ok=True)
    for name, xor, game_rel, _ in FILES:
        lines = load_lines(source_path(game_rel, game), xor)
        out_path = os.path.join(JSON_DIR, os.path.splitext(name)[0] + ".json")
        old = {}
        if os.path.exists(out_path):
            for e in json.load(open(out_path, encoding="utf-8")):
                old[(e["line"], e["seg"])] = e.get("translated")
        entries = []
        for ln, line in enumerate(lines, 1):
            body = line.rstrip("\r\n")
            if body.lstrip().startswith("@"):
                continue
            for seg, m in enumerate(RUN.finditer(body)):
                first = body.split(None, 1)[0] if body.split() else ""
                protected = bool(PROTECT_KEY.search(first))
                entry = {
                    "line": ln, "seg": seg, "key": first,
                    "original": m.group(0),
                    "translated": None if protected else old.get((ln, seg)),
                    "context": body,
                }
                if protected:
                    entry["note"] = "script variable name -- do not translate"
                entries.append(entry)
        with open(out_path, "w", encoding="utf-8") as fh:
            json.dump(entries, fh, ensure_ascii=False, indent=1)
        kept = sum(1 for e in entries if e["translated"] is not None)
        print(f"{name}: {len(entries)} segments -> {out_path}"
              + (f" (kept {kept} existing translations)" if kept else ""))


def build(game=DEFAULT_GAME):
    name_map = load_name_map()
    for name, xor, game_rel, use_names in FILES:
        lines = load_lines(source_path(game_rel, game), xor)
        json_path = os.path.join(JSON_DIR, os.path.splitext(name)[0] + ".json")
        entries = json.load(open(json_path, encoding="utf-8"))
        applied = 0
        # Keep scenario names and the engine's name lookup tables identical. The shared
        # glossary is authoritative; a local UI translation is only a fallback for names
        # absent from (or left null in) names.json.
        by_line = {}
        for e in entries:
            if PROTECT_KEY.search(e.get("key", "")):
                continue  # script variable name: keep the original, never translate
            if use_names and name_map.get(e["original"]) is not None:
                e = dict(e, translated=name_map[e["original"]])
            if e["translated"] is not None:
                if name == "config.fxf" and any(c in " \t\r\n" for c in e["translated"]):
                    raise SystemExit(
                        f"{name} line {e['line']}: translation contains ASCII whitespace; "
                        "FXF values must be a single token"
                    )
                by_line.setdefault(e["line"], []).append(e)
        for ln, todo in by_line.items():
            body = lines[ln - 1]
            eol = body[len(body.rstrip("\r\n")):]
            body = body.rstrip("\r\n")
            runs = list(RUN.finditer(body))
            for e in sorted(todo, key=lambda x: -x["seg"]):
                m = runs[e["seg"]]
                if m.group(0) != e["original"]:
                    raise SystemExit(f"{name} line {ln} seg {e['seg']}: original text "
                                     f"changed ({m.group(0)!r} != {e['original']!r}); re-extract")
                t = e["translated"]
                try:
                    t.encode("cp932")
                except UnicodeEncodeError as ex:
                    raise SystemExit(f"{name} line {ln}: translation not SJIS-encodable: {ex}")
                body = body[:m.start()] + t + body[m.end():]
                applied += 1
            lines[ln - 1] = body + eol
        data = "".join(lines).encode("cp932")
        if xor:
            data = bytes(b ^ 0xFF for b in data)
        deploy = os.path.join(game, game_rel)
        os.makedirs(os.path.dirname(deploy), exist_ok=True)
        with open(deploy, "wb") as fh:
            fh.write(data)
        print(f"{name}: {applied} translations applied -> {deploy}")


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="UI/system text extract/build (see module docstring)")
    ap.add_argument("cmd", choices=["extract", "build"])
    ap.add_argument("--game", default=DEFAULT_GAME,
                    help="game folder (source via <asset>.orig; deploy target)")
    a = ap.parse_args()
    (extract if a.cmd == "extract" else build)(a.game)
